# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ArticleResponse(BaseModel):
    """
    ArticleResponse
    """ # noqa: E501
    confidence: Union[StrictFloat, StrictInt]
    content: Optional[StrictStr] = None
    contention_count: StrictInt
    created_at: StrictStr
    domain_path: List[StrictStr]
    epistemic_type: Optional[StrictStr] = None
    id: StrictStr
    metadata: Dict[str, Any]
    modified_at: StrictStr
    node_type: StrictStr
    pinned: StrictBool
    stale: Optional[StrictBool] = Field(default=None, description="`true` when newer unlinked sources exist in the same domain — the article may benefit from recompilation.  `None` when not computed (e.g. in list responses).")
    status: StrictStr
    title: Optional[StrictStr] = None
    usage_score: Union[StrictFloat, StrictInt]
    version: StrictInt
    __properties: ClassVar[List[str]] = ["confidence", "content", "contention_count", "created_at", "domain_path", "epistemic_type", "id", "metadata", "modified_at", "node_type", "pinned", "stale", "status", "title", "usage_score", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArticleResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if content (nullable) is None
        # and model_fields_set contains the field
        if self.content is None and "content" in self.model_fields_set:
            _dict['content'] = None

        # set to None if epistemic_type (nullable) is None
        # and model_fields_set contains the field
        if self.epistemic_type is None and "epistemic_type" in self.model_fields_set:
            _dict['epistemic_type'] = None

        # set to None if stale (nullable) is None
        # and model_fields_set contains the field
        if self.stale is None and "stale" in self.model_fields_set:
            _dict['stale'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArticleResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "confidence": obj.get("confidence"),
            "content": obj.get("content"),
            "contention_count": obj.get("contention_count"),
            "created_at": obj.get("created_at"),
            "domain_path": obj.get("domain_path"),
            "epistemic_type": obj.get("epistemic_type"),
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "modified_at": obj.get("modified_at"),
            "node_type": obj.get("node_type"),
            "pinned": obj.get("pinned"),
            "stale": obj.get("stale"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "usage_score": obj.get("usage_score"),
            "version": obj.get("version")
        })
        return _obj


