# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class IngestRequest(BaseModel):
    """
    Request to ingest a new source.
    """ # noqa: E501
    capture_method: Optional[StrictStr] = Field(default=None, description="Intentionality classifier: `\"manual\"` | `\"auto\"` | `\"system\"` | `None`.  - `\"manual\"` — caller explicitly requested ingestion (e.g. `memory_store`,   direct `source_ingest`).  Boosts reliability for low-signal types. - `\"auto\"` — ambient / heuristic capture.  Lowers reliability for noisy types. - `\"system\"` — generated by an internal system process.  Keeps defaults. - `None` — backward-compatible: use type-only defaults unchanged.")
    content: StrictStr
    metadata: Dict[str, Any]
    reliability: Optional[Union[StrictFloat, StrictInt]] = None
    session_id: Optional[StrictStr] = None
    source_type: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["capture_method", "content", "metadata", "reliability", "session_id", "source_type", "title"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IngestRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if capture_method (nullable) is None
        # and model_fields_set contains the field
        if self.capture_method is None and "capture_method" in self.model_fields_set:
            _dict['capture_method'] = None

        # set to None if reliability (nullable) is None
        # and model_fields_set contains the field
        if self.reliability is None and "reliability" in self.model_fields_set:
            _dict['reliability'] = None

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['session_id'] = None

        # set to None if source_type (nullable) is None
        # and model_fields_set contains the field
        if self.source_type is None and "source_type" in self.model_fields_set:
            _dict['source_type'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IngestRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "capture_method": obj.get("capture_method"),
            "content": obj.get("content"),
            "metadata": obj.get("metadata"),
            "reliability": obj.get("reliability"),
            "session_id": obj.get("session_id"),
            "source_type": obj.get("source_type"),
            "title": obj.get("title")
        })
        return _obj


