# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MaintenanceRequest(BaseModel):
    """
    MaintenanceRequest
    """ # noqa: E501
    evict_count: Optional[StrictInt] = None
    evict_if_over_capacity: Optional[StrictBool] = None
    graph_embeddings_method: Optional[StrictStr] = Field(default=None, description="Embedding method: `\"node2vec\"`, `\"spectral\"`, or `\"both\"` (default).")
    process_queue: Optional[StrictBool] = None
    recompute_graph_embeddings: Optional[StrictBool] = Field(default=None, description="When `true`, enqueue a `recompute_graph_embeddings` task. Pass `method` in the sub-field to select `\"node2vec\"`, `\"spectral\"`, or `\"both\"`.")
    recompute_scores: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["evict_count", "evict_if_over_capacity", "graph_embeddings_method", "process_queue", "recompute_graph_embeddings", "recompute_scores"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MaintenanceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if evict_count (nullable) is None
        # and model_fields_set contains the field
        if self.evict_count is None and "evict_count" in self.model_fields_set:
            _dict['evict_count'] = None

        # set to None if evict_if_over_capacity (nullable) is None
        # and model_fields_set contains the field
        if self.evict_if_over_capacity is None and "evict_if_over_capacity" in self.model_fields_set:
            _dict['evict_if_over_capacity'] = None

        # set to None if graph_embeddings_method (nullable) is None
        # and model_fields_set contains the field
        if self.graph_embeddings_method is None and "graph_embeddings_method" in self.model_fields_set:
            _dict['graph_embeddings_method'] = None

        # set to None if process_queue (nullable) is None
        # and model_fields_set contains the field
        if self.process_queue is None and "process_queue" in self.model_fields_set:
            _dict['process_queue'] = None

        # set to None if recompute_graph_embeddings (nullable) is None
        # and model_fields_set contains the field
        if self.recompute_graph_embeddings is None and "recompute_graph_embeddings" in self.model_fields_set:
            _dict['recompute_graph_embeddings'] = None

        # set to None if recompute_scores (nullable) is None
        # and model_fields_set contains the field
        if self.recompute_scores is None and "recompute_scores" in self.model_fields_set:
            _dict['recompute_scores'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MaintenanceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "evict_count": obj.get("evict_count"),
            "evict_if_over_capacity": obj.get("evict_if_over_capacity"),
            "graph_embeddings_method": obj.get("graph_embeddings_method"),
            "process_queue": obj.get("process_queue"),
            "recompute_graph_embeddings": obj.get("recompute_graph_embeddings"),
            "recompute_scores": obj.get("recompute_scores")
        })
        return _obj


