# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SearchStrategy(str, Enum):
    """
    Adaptive fusion strategy — controls the relative weighting of the four search dimensions for different query types.  When [`SearchRequest::weights`] is explicitly provided it always takes precedence; `strategy` only applies when no explicit weights are given.
    """

    """
    allowed enum values
    """
    BALANCED = 'balanced'
    PRECISE = 'precise'
    EXPLORATORY = 'exploratory'
    GRAPH = 'graph'
    STRUCTURAL = 'structural'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SearchStrategy from a JSON string"""
        return cls(json.loads(json_str))


