# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from covalence.models.search_intent import SearchIntent
from covalence.models.search_mode import SearchMode
from covalence.models.search_strategy import SearchStrategy
from covalence.models.weights_input import WeightsInput
from typing import Optional, Set
from typing_extensions import Self

class SearchRequest(BaseModel):
    """
    Request body for POST /search.
    """ # noqa: E501
    after: Optional[StrictStr] = Field(default=None, description="Include only nodes whose `created_at` is strictly after this timestamp. When `None`, no lower-bound date filter is applied.")
    before: Optional[StrictStr] = Field(default=None, description="Include only nodes whose `created_at` is strictly before this timestamp. When `None`, no upper-bound date filter is applied.")
    domain_path: Optional[List[StrictStr]] = Field(default=None, description="Optional domain-path filter. When set, only nodes whose `domain_path` array shares at least one element with this list are returned. Nodes with an empty or NULL `domain_path` are excluded when filtering.")
    embedding: Optional[List[Union[StrictFloat, StrictInt]]] = None
    intent: Optional[SearchIntent] = None
    limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    max_hops: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Maximum graph traversal hops (1-3, default 1). Higher values discover structurally distant but related nodes via edge chains.  When absent, the effective default is determined by `strategy`: - [`SearchStrategy::Graph`] → 2 hops - All other strategies → 1 hop  Explicit `max_hops` always wins over the strategy-derived default.")
    min_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Minimum score threshold (covalence#33). Results with a final score strictly below this value are filtered out before returning. When `None` (the default), all results are returned regardless of score. Useful for precision queries: set to 0.6 to avoid weak matches.")
    mode: Optional[SearchMode] = Field(default=None, description="Search mode — defaults to [`SearchMode::Standard`].")
    node_types: Optional[List[StrictStr]] = None
    query: StrictStr
    recency_bias: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Recency bias factor (0.0–1.0). Higher values favor newer content. At 0.0 (default), freshness gets 5% weight (current behavior). At 1.0, freshness gets 40% weight (strongly favor recent).")
    session_id: Optional[StrictStr] = None
    strategy: Optional[SearchStrategy] = Field(default=None, description="Search strategy — adjusts dimension weights for different query types. Overrides `weights` when set to a non-`Balanced` value. When both `weights` and `strategy` are provided, `weights` wins.")
    weights: Optional[WeightsInput] = None
    __properties: ClassVar[List[str]] = ["after", "before", "domain_path", "embedding", "intent", "limit", "max_hops", "min_score", "mode", "node_types", "query", "recency_bias", "session_id", "strategy", "weights"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of weights
        if self.weights:
            _dict['weights'] = self.weights.to_dict()
        # set to None if after (nullable) is None
        # and model_fields_set contains the field
        if self.after is None and "after" in self.model_fields_set:
            _dict['after'] = None

        # set to None if before (nullable) is None
        # and model_fields_set contains the field
        if self.before is None and "before" in self.model_fields_set:
            _dict['before'] = None

        # set to None if domain_path (nullable) is None
        # and model_fields_set contains the field
        if self.domain_path is None and "domain_path" in self.model_fields_set:
            _dict['domain_path'] = None

        # set to None if embedding (nullable) is None
        # and model_fields_set contains the field
        if self.embedding is None and "embedding" in self.model_fields_set:
            _dict['embedding'] = None

        # set to None if intent (nullable) is None
        # and model_fields_set contains the field
        if self.intent is None and "intent" in self.model_fields_set:
            _dict['intent'] = None

        # set to None if max_hops (nullable) is None
        # and model_fields_set contains the field
        if self.max_hops is None and "max_hops" in self.model_fields_set:
            _dict['max_hops'] = None

        # set to None if min_score (nullable) is None
        # and model_fields_set contains the field
        if self.min_score is None and "min_score" in self.model_fields_set:
            _dict['min_score'] = None

        # set to None if mode (nullable) is None
        # and model_fields_set contains the field
        if self.mode is None and "mode" in self.model_fields_set:
            _dict['mode'] = None

        # set to None if node_types (nullable) is None
        # and model_fields_set contains the field
        if self.node_types is None and "node_types" in self.model_fields_set:
            _dict['node_types'] = None

        # set to None if recency_bias (nullable) is None
        # and model_fields_set contains the field
        if self.recency_bias is None and "recency_bias" in self.model_fields_set:
            _dict['recency_bias'] = None

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['session_id'] = None

        # set to None if strategy (nullable) is None
        # and model_fields_set contains the field
        if self.strategy is None and "strategy" in self.model_fields_set:
            _dict['strategy'] = None

        # set to None if weights (nullable) is None
        # and model_fields_set contains the field
        if self.weights is None and "weights" in self.model_fields_set:
            _dict['weights'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "after": obj.get("after"),
            "before": obj.get("before"),
            "domain_path": obj.get("domain_path"),
            "embedding": obj.get("embedding"),
            "intent": obj.get("intent"),
            "limit": obj.get("limit"),
            "max_hops": obj.get("max_hops"),
            "min_score": obj.get("min_score"),
            "mode": obj.get("mode"),
            "node_types": obj.get("node_types"),
            "query": obj.get("query"),
            "recency_bias": obj.get("recency_bias"),
            "session_id": obj.get("session_id"),
            "strategy": obj.get("strategy"),
            "weights": WeightsInput.from_dict(obj["weights"]) if obj.get("weights") is not None else None
        })
        return _obj


