# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SearchIntent(str, Enum):
    """
    Search intent for intent-aware retrieval routing.
    """

    """
    allowed enum values
    """
    FACTUAL = 'factual'
    TEMPORAL = 'temporal'
    CAUSAL = 'causal'
    ENTITY = 'entity'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SearchIntent from a JSON string"""
        return cls(json.loads(json_str))


