# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SourceResponse(BaseModel):
    """
    Response envelope for a source.
    """ # noqa: E501
    capture_method: Optional[StrictStr] = Field(default=None, description="How this source was captured — read from `metadata[\"capture_method\"]`. `None` when absent (e.g. sources ingested before this field existed).")
    confidence: Union[StrictFloat, StrictInt]
    content: StrictStr
    created_at: StrictStr
    fingerprint: StrictStr
    id: StrictStr
    metadata: Dict[str, Any]
    modified_at: StrictStr
    node_type: StrictStr
    reliability: Union[StrictFloat, StrictInt]
    source_type: Optional[StrictStr] = None
    status: StrictStr
    title: Optional[StrictStr] = None
    version: StrictInt
    __properties: ClassVar[List[str]] = ["capture_method", "confidence", "content", "created_at", "fingerprint", "id", "metadata", "modified_at", "node_type", "reliability", "source_type", "status", "title", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SourceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if capture_method (nullable) is None
        # and model_fields_set contains the field
        if self.capture_method is None and "capture_method" in self.model_fields_set:
            _dict['capture_method'] = None

        # set to None if source_type (nullable) is None
        # and model_fields_set contains the field
        if self.source_type is None and "source_type" in self.model_fields_set:
            _dict['source_type'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SourceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "capture_method": obj.get("capture_method"),
            "confidence": obj.get("confidence"),
            "content": obj.get("content"),
            "created_at": obj.get("created_at"),
            "fingerprint": obj.get("fingerprint"),
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "modified_at": obj.get("modified_at"),
            "node_type": obj.get("node_type"),
            "reliability": obj.get("reliability"),
            "source_type": obj.get("source_type"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "version": obj.get("version")
        })
        return _obj


