# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class WeightsInput(BaseModel):
    """
    WeightsInput
    """ # noqa: E501
    graph: Optional[Union[StrictFloat, StrictInt]] = None
    lexical: Optional[Union[StrictFloat, StrictInt]] = None
    structural: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Weight for the structural similarity dimension (covalence#52). When omitted, defaults to `0.0` when explicit weights are provided, or the strategy preset when using a strategy.")
    vector: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["graph", "lexical", "structural", "vector"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WeightsInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if graph (nullable) is None
        # and model_fields_set contains the field
        if self.graph is None and "graph" in self.model_fields_set:
            _dict['graph'] = None

        # set to None if lexical (nullable) is None
        # and model_fields_set contains the field
        if self.lexical is None and "lexical" in self.model_fields_set:
            _dict['lexical'] = None

        # set to None if structural (nullable) is None
        # and model_fields_set contains the field
        if self.structural is None and "structural" in self.model_fields_set:
            _dict['structural'] = None

        # set to None if vector (nullable) is None
        # and model_fields_set contains the field
        if self.vector is None and "vector" in self.model_fields_set:
            _dict['vector'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WeightsInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "graph": obj.get("graph"),
            "lexical": obj.get("lexical"),
            "structural": obj.get("structural"),
            "vector": obj.get("vector")
        })
        return _obj


