//! OpenAPI specification via utoipa.

use utoipa::OpenApi;

use crate::handlers::{admin, analysis, dto, edges, mcp, nodes, search, sources};

/// OpenAPI documentation for the Covalence API.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Covalence API",
        version = "0.1.0",
        description = "Hybrid GraphRAG knowledge engine API",
    ),
    servers(
        (url = "/api/v1", description = "Versioned API"),
    ),
    paths(
        // Sources
        sources::create_source,
        sources::get_source,
        sources::list_sources,
        sources::get_source_chunks,
        sources::delete_source,
        sources::reprocess_source,
        // Search
        search::search,
        search::search_feedback,
        // Nodes
        nodes::get_node,
        nodes::get_neighborhood,
        nodes::get_provenance,
        nodes::resolve_node,
        nodes::merge_nodes,
        nodes::split_node,
        nodes::correct_node,
        nodes::annotate_node,
        nodes::list_landmarks,
        // Edges
        edges::get_edge,
        edges::correct_edge,
        edges::delete_edge,
        // Graph
        admin::graph_stats,
        admin::graph_communities,
        admin::graph_topology,
        // Audit
        admin::audit_log,
        // MCP
        mcp::list_tools_handler,
        mcp::call_tool,
        // Admin
        admin::reload_graph,
        admin::publish_source,
        admin::trigger_consolidation,
        admin::trigger_raptor,
        admin::garbage_collect,
        admin::health,
        admin::metrics,
        admin::list_traces,
        admin::replay_trace,
        admin::clear_cache,
        admin::knowledge_gaps,
        admin::config_audit,
        admin::synthesize_cooccurrence,
        admin::cluster_ontology,
        admin::resolve_tier5,
        admin::cleanup_noise_entities,
        admin::backfill_node_embeddings,
        admin::seed_opinions,
        admin::summarize_code_nodes,
        admin::bridge_code_to_concepts,
        // Analysis
        analysis::bootstrap_components,
        analysis::link_domains,
        analysis::coverage_analysis,
        analysis::detect_erosion,
        analysis::blast_radius,
        analysis::whitespace_roadmap,
        analysis::verify_implementation,
        analysis::critique,
    ),
    components(schemas(
        dto::CreateSourceRequest,
        dto::CreateSourceResponse,
        dto::SourceResponse,
        dto::DeleteSourceResponse,
        dto::ReprocessSourceResponse,
        dto::ChunkResponse,
        dto::PaginationParams,
        dto::SearchMode,
        dto::SearchGranularity,
        dto::SearchRequest,
        dto::SearchResultResponse,
        dto::RelatedEntityResponse,
        dto::ContextItemResponse,
        dto::ContextResponse,
        dto::SearchApiResponse,
        dto::NodeResponse,
        dto::GetNodeParams,
        dto::NodeExplanation,
        dto::NodeDetailResponse,
        dto::NeighborhoodParams,
        dto::ResolveNodeRequest,
        dto::MergeNodesRequest,
        dto::MergeNodesResponse,
        dto::SplitNodeRequest,
        dto::SplitSpecRequest,
        dto::SplitNodeResponse,
        dto::ProvenanceResponse,
        dto::EdgeResponse,
        dto::GraphStatsResponse,
        dto::CommunityResponse,
        dto::TopologyResponse,
        dto::DomainResponse,
        dto::DomainLinkResponse,
        dto::AuditLogResponse,
        dto::ReloadResponse,
        dto::PublishResponse,
        dto::ConsolidateResponse,
        dto::RaptorResponse,
        dto::GcResponse,
        dto::HealthResponse,
        dto::MetricsResponse,
        dto::CorrectNodeRequest,
        dto::CorrectEdgeRequest,
        dto::DeleteEdgeParams,
        dto::AnnotateNodeRequest,
        dto::SearchFeedbackRequest,
        dto::CurationResponse,
        dto::FeedbackResponse,
        dto::SearchTraceResponse,
        dto::TraceReplayResponse,
        dto::KnowledgeGapParams,
        dto::KnowledgeGapItem,
        dto::KnowledgeGapsResponse,
        dto::ConfigAuditResponse,
        dto::SidecarHealthResponse,
        dto::CooccurrenceRequest,
        dto::CooccurrenceResponse,
        dto::OntologyClusterRequest,
        dto::OntologyClusterItem,
        dto::OntologyClusterResponse,
        dto::Tier5ResolveRequest,
        dto::Tier5ResolveResponse,
        dto::NoiseCleanupRequest,
        dto::NoiseCleanupResponse,
        dto::NoiseEntityItem,
        dto::CodeSummaryResponse,
        dto::BridgeRequest,
        dto::BridgeResponse,
        dto::BootstrapResponse,
        dto::LinkDomainsRequest,
        dto::LinkDomainsResponse,
        dto::CoverageItemResponse,
        dto::CoverageResponse,
        dto::ErosionRequest,
        dto::DivergentNodeResponse,
        dto::ErosionItemResponse,
        dto::ErosionResponse,
        dto::BlastRadiusRequest,
        dto::AffectedNodeResponse,
        dto::BlastRadiusHopResponse,
        dto::BlastRadiusResponse,
        dto::WhitespaceRequest,
        dto::WhitespaceNodeResponse,
        dto::WhitespaceGapResponse,
        dto::WhitespaceResponse,
        dto::VerifyRequest,
        dto::VerificationMatchResponse,
        dto::VerifyResponse,
        dto::CritiqueRequest,
        dto::CritiqueEvidenceResponse,
        dto::CounterArgumentResponse,
        dto::SupportingArgumentResponse,
        dto::CritiqueSynthesisResponse,
        dto::CritiqueResponse,
        mcp::McpTool,
        mcp::McpToolCall,
        mcp::McpToolResult,
        mcp::McpContent,
    )),
    tags(
        (name = "sources", description = "Source ingestion and management"),
        (name = "search", description = "Multi-dimensional fused search"),
        (name = "nodes", description = "Graph node operations"),
        (name = "edges", description = "Graph edge operations"),
        (name = "graph", description = "Graph analysis endpoints"),
        (name = "mcp", description = "Model Context Protocol tool interface"),
        (name = "admin", description = "Administrative operations"),
        (name = "analysis", description = "Cross-domain analysis"),
    )
)]
pub struct ApiDoc;
