# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.source_response import SourceResponse

class TestSourceResponse(unittest.TestCase):
    """SourceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SourceResponse:
        """Test SourceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SourceResponse`
        """
        model = SourceResponse()
        if include_optional:
            return SourceResponse(
                capture_method = '',
                confidence = 1.337,
                content = '',
                created_at = '',
                fingerprint = '',
                id = '',
                metadata = None,
                modified_at = '',
                node_type = '',
                reliability = 1.337,
                source_type = '',
                status = '',
                title = '',
                version = 56
            )
        else:
            return SourceResponse(
                confidence = 1.337,
                content = '',
                created_at = '',
                fingerprint = '',
                id = '',
                metadata = None,
                modified_at = '',
                node_type = '',
                reliability = 1.337,
                status = '',
                version = 56,
        )
        """

    def testSourceResponse(self):
        """Test SourceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
