# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.search_intent import SearchIntent

class TestSearchIntent(unittest.TestCase):
    """SearchIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchIntent(self):
        """Test SearchIntent"""
        # inst = SearchIntent()

if __name__ == '__main__':
    unittest.main()
