# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.node_stats import NodeStats

class TestNodeStats(unittest.TestCase):
    """NodeStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeStats:
        """Test NodeStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeStats`
        """
        model = NodeStats()
        if include_optional:
            return NodeStats(
                active = 56,
                archived = 56,
                articles = 56,
                pinned = 56,
                sessions = 56,
                sources = 56,
                total = 56
            )
        else:
            return NodeStats(
                active = 56,
                archived = 56,
                articles = 56,
                pinned = 56,
                sessions = 56,
                sources = 56,
                total = 56,
        )
        """

    def testNodeStats(self):
        """Test NodeStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
