# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.store_memory_request import StoreMemoryRequest

class TestStoreMemoryRequest(unittest.TestCase):
    """StoreMemoryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StoreMemoryRequest:
        """Test StoreMemoryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StoreMemoryRequest`
        """
        model = StoreMemoryRequest()
        if include_optional:
            return StoreMemoryRequest(
                content = '',
                context = '',
                importance = 1.337,
                supersedes_id = '',
                tags = [
                    ''
                    ]
            )
        else:
            return StoreMemoryRequest(
                content = '',
        )
        """

    def testStoreMemoryRequest(self):
        """Test StoreMemoryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
