# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.compile_request import CompileRequest

class TestCompileRequest(unittest.TestCase):
    """CompileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompileRequest:
        """Test CompileRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompileRequest`
        """
        model = CompileRequest()
        if include_optional:
            return CompileRequest(
                compilation_focus = '',
                source_ids = [
                    ''
                    ],
                title_hint = ''
            )
        else:
            return CompileRequest(
                source_ids = [
                    ''
                    ],
        )
        """

    def testCompileRequest(self):
        """Test CompileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
