# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.weights_input import WeightsInput

class TestWeightsInput(unittest.TestCase):
    """WeightsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WeightsInput:
        """Test WeightsInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WeightsInput`
        """
        model = WeightsInput()
        if include_optional:
            return WeightsInput(
                graph = 1.337,
                lexical = 1.337,
                structural = 1.337,
                vector = 1.337
            )
        else:
            return WeightsInput(
        )
        """

    def testWeightsInput(self):
        """Test WeightsInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
