# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.article_response import ArticleResponse

class TestArticleResponse(unittest.TestCase):
    """ArticleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArticleResponse:
        """Test ArticleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArticleResponse`
        """
        model = ArticleResponse()
        if include_optional:
            return ArticleResponse(
                confidence = 1.337,
                content = '',
                contention_count = 56,
                created_at = '',
                domain_path = [
                    ''
                    ],
                epistemic_type = '',
                id = '',
                metadata = None,
                modified_at = '',
                node_type = '',
                pinned = True,
                stale = True,
                status = '',
                title = '',
                usage_score = 1.337,
                version = 56
            )
        else:
            return ArticleResponse(
                confidence = 1.337,
                contention_count = 56,
                created_at = '',
                domain_path = [
                    ''
                    ],
                id = '',
                metadata = None,
                modified_at = '',
                node_type = '',
                pinned = True,
                status = '',
                usage_score = 1.337,
                version = 56,
        )
        """

    def testArticleResponse(self):
        """Test ArticleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
