# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.stats_response import StatsResponse

class TestStatsResponse(unittest.TestCase):
    """StatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsResponse:
        """Test StatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsResponse`
        """
        model = StatsResponse()
        if include_optional:
            return StatsResponse(
                edges = covalence.models.edge_stats.EdgeStats(
                    age_count = 56, 
                    in_sync = True, 
                    sql_count = 56, ),
                embeddings = covalence.models.embedding_stats.EmbeddingStats(
                    nodes_without = 56, 
                    total = 56, ),
                nodes = covalence.models.node_stats.NodeStats(
                    active = 56, 
                    archived = 56, 
                    articles = 56, 
                    pinned = 56, 
                    sessions = 56, 
                    sources = 56, 
                    total = 56, ),
                queue = covalence.models.queue_stats.QueueStats(
                    completed_24h = 56, 
                    failed = 56, 
                    pending = 56, 
                    processing = 56, )
            )
        else:
            return StatsResponse(
                edges = covalence.models.edge_stats.EdgeStats(
                    age_count = 56, 
                    in_sync = True, 
                    sql_count = 56, ),
                embeddings = covalence.models.embedding_stats.EmbeddingStats(
                    nodes_without = 56, 
                    total = 56, ),
                nodes = covalence.models.node_stats.NodeStats(
                    active = 56, 
                    archived = 56, 
                    articles = 56, 
                    pinned = 56, 
                    sessions = 56, 
                    sources = 56, 
                    total = 56, ),
                queue = covalence.models.queue_stats.QueueStats(
                    completed_24h = 56, 
                    failed = 56, 
                    pending = 56, 
                    processing = 56, ),
        )
        """

    def testStatsResponse(self):
        """Test StatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
