# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_admin_maintenance(self) -> None:
        """Test case for admin_maintenance

        POST /admin/maintenance
        """
        pass

    def test_admin_stats(self) -> None:
        """Test case for admin_stats

        GET /admin/stats
        """
        pass


if __name__ == '__main__':
    unittest.main()
