# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.search_request import SearchRequest

class TestSearchRequest(unittest.TestCase):
    """SearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchRequest:
        """Test SearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchRequest`
        """
        model = SearchRequest()
        if include_optional:
            return SearchRequest(
                after = '',
                before = '',
                domain_path = [
                    ''
                    ],
                embedding = [
                    1.337
                    ],
                intent = 'factual',
                limit = 0,
                max_hops = 0,
                min_score = 1.337,
                mode = 'standard',
                node_types = [
                    ''
                    ],
                query = '',
                recency_bias = 1.337,
                session_id = '',
                strategy = 'balanced',
                weights = covalence.models.weights_input.WeightsInput(
                    graph = 1.337, 
                    lexical = 1.337, 
                    structural = 1.337, 
                    vector = 1.337, )
            )
        else:
            return SearchRequest(
                query = '',
        )
        """

    def testSearchRequest(self):
        """Test SearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
