# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.api.sources_api import SourcesApi


class TestSourcesApi(unittest.TestCase):
    """SourcesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SourcesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_source(self) -> None:
        """Test case for delete_source

        DELETE /sources/{id}
        """
        pass

    def test_get_source(self) -> None:
        """Test case for get_source

        GET /sources/{id}
        """
        pass

    def test_ingest_source(self) -> None:
        """Test case for ingest_source

        POST /sources
        """
        pass


if __name__ == '__main__':
    unittest.main()
