# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.maintenance_response import MaintenanceResponse

class TestMaintenanceResponse(unittest.TestCase):
    """MaintenanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaintenanceResponse:
        """Test MaintenanceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaintenanceResponse`
        """
        model = MaintenanceResponse()
        if include_optional:
            return MaintenanceResponse(
                actions_taken = [
                    ''
                    ]
            )
        else:
            return MaintenanceResponse(
                actions_taken = [
                    ''
                    ],
        )
        """

    def testMaintenanceResponse(self):
        """Test MaintenanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
