# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.maintenance_request import MaintenanceRequest

class TestMaintenanceRequest(unittest.TestCase):
    """MaintenanceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaintenanceRequest:
        """Test MaintenanceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaintenanceRequest`
        """
        model = MaintenanceRequest()
        if include_optional:
            return MaintenanceRequest(
                evict_count = 56,
                evict_if_over_capacity = True,
                graph_embeddings_method = '',
                process_queue = True,
                recompute_graph_embeddings = True,
                recompute_scores = True
            )
        else:
            return MaintenanceRequest(
        )
        """

    def testMaintenanceRequest(self):
        """Test MaintenanceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
