# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.merge_request import MergeRequest

class TestMergeRequest(unittest.TestCase):
    """MergeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MergeRequest:
        """Test MergeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MergeRequest`
        """
        model = MergeRequest()
        if include_optional:
            return MergeRequest(
                article_id_a = '',
                article_id_b = ''
            )
        else:
            return MergeRequest(
                article_id_a = '',
                article_id_b = '',
        )
        """

    def testMergeRequest(self):
        """Test MergeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
