# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.memory import Memory

class TestMemory(unittest.TestCase):
    """Memory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Memory:
        """Test Memory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Memory`
        """
        model = Memory()
        if include_optional:
            return Memory(
                confidence = 1.337,
                content = '',
                context = '',
                created_at = '',
                forgotten = True,
                id = '',
                importance = 1.337,
                tags = None
            )
        else:
            return Memory(
                confidence = 1.337,
                content = '',
                created_at = '',
                forgotten = True,
                id = '',
                importance = 1.337,
                tags = None,
        )
        """

    def testMemory(self):
        """Test Memory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
