# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.api.memory_api import MemoryApi


class TestMemoryApi(unittest.TestCase):
    """MemoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemoryApi()

    def tearDown(self) -> None:
        pass

    def test_recall_memory(self) -> None:
        """Test case for recall_memory

        POST /memory/search
        """
        pass

    def test_store_memory(self) -> None:
        """Test case for store_memory

        POST /memory
        """
        pass


if __name__ == '__main__':
    unittest.main()
