# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.models.queue_stats import QueueStats

class TestQueueStats(unittest.TestCase):
    """QueueStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueueStats:
        """Test QueueStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueueStats`
        """
        model = QueueStats()
        if include_optional:
            return QueueStats(
                completed_24h = 56,
                failed = 56,
                pending = 56,
                processing = 56
            )
        else:
            return QueueStats(
                completed_24h = 56,
                failed = 56,
                pending = 56,
                processing = 56,
        )
        """

    def testQueueStats(self):
        """Test QueueStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
