# coding: utf-8

"""
    Covalence Knowledge Engine

    Epistemic knowledge management API — sources, articles, search, and memory

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from covalence.api.articles_api import ArticlesApi


class TestArticlesApi(unittest.TestCase):
    """ArticlesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArticlesApi()

    def tearDown(self) -> None:
        pass

    def test_compile_article(self) -> None:
        """Test case for compile_article

        POST /articles/compile
        """
        pass

    def test_get_article(self) -> None:
        """Test case for get_article

        GET /articles/{id}
        """
        pass

    def test_merge_articles(self) -> None:
        """Test case for merge_articles

        POST /articles/merge
        """
        pass


if __name__ == '__main__':
    unittest.main()
