//! Source lifecycle — ingest, get, list, delete (SPEC §5.4, §8.1).

use chrono::Utc;
use sha2::{Digest, Sha256};
use sqlx::{PgPool, Row, postgres::PgRow};
use uuid::Uuid;

use crate::errors::*;
use crate::graph::{GraphRepository, SqlGraphRepository};
use crate::models::*;

/// Request to ingest a new source.
#[derive(Debug, serde::Deserialize, utoipa::ToSchema)]
pub struct IngestRequest {
    pub content: String,
    pub source_type: Option<String>,
    pub title: Option<String>,
    #[schema(value_type = Object)]
    pub metadata: Option<serde_json::Value>,
    #[schema(value_type = Option<String>)]
    pub session_id: Option<Uuid>,
    pub reliability: Option<f32>,
    /// Intentionality classifier: `"manual"` | `"auto"` | `"system"` | `None`.
    ///
    /// - `"manual"` — caller explicitly requested ingestion (e.g. `memory_store`,
    ///   direct `source_ingest`).  Boosts reliability for low-signal types.
    /// - `"auto"` — ambient / heuristic capture.  Lowers reliability for noisy types.
    /// - `"system"` — generated by an internal system process.  Keeps defaults.
    /// - `None` — backward-compatible: use type-only defaults unchanged.
    pub capture_method: Option<String>,
}

/// Paginated list params.
#[derive(Debug, serde::Deserialize, Default)]
pub struct ListParams {
    pub limit: Option<i64>,
    pub cursor: Option<Uuid>,
    pub source_type: Option<String>,
    pub status: Option<String>,
    pub q: Option<String>,
}

/// Response envelope for a source.
#[derive(Debug, serde::Serialize, utoipa::ToSchema)]
pub struct SourceResponse {
    #[schema(value_type = String)]
    pub id: Uuid,
    pub node_type: String,
    pub title: Option<String>,
    pub content: String,
    pub source_type: Option<String>,
    pub status: String,
    pub confidence: f32,
    pub reliability: f32,
    pub fingerprint: String,
    #[schema(value_type = Object)]
    pub metadata: serde_json::Value,
    pub version: i32,
    #[schema(value_type = String)]
    pub created_at: chrono::DateTime<Utc>,
    #[schema(value_type = String)]
    pub modified_at: chrono::DateTime<Utc>,
    /// How this source was captured — read from `metadata["capture_method"]`.
    /// `None` when absent (e.g. sources ingested before this field existed).
    pub capture_method: Option<String>,
}

pub struct SourceService {
    pool: PgPool,
    graph: SqlGraphRepository,
    namespace: String,
}

impl SourceService {
    pub fn new(pool: PgPool) -> Self {
        let graph = SqlGraphRepository::new(pool.clone());
        Self {
            pool,
            graph,
            namespace: "default".into(),
        }
    }

    /// Set the namespace for this service instance.
    pub fn with_namespace(mut self, ns: String) -> Self {
        self.namespace = ns;
        self
    }

    /// Ingest a source — idempotent via SHA-256 fingerprint (SPEC §8.1 fast path).
    pub async fn ingest(&self, req: IngestRequest) -> AppResult<SourceResponse> {
        // 1. Compute fingerprint
        let fingerprint = hex::encode(Sha256::digest(req.content.as_bytes()));

        // 2. Check for existing source with same fingerprint (idempotent, scoped to namespace)
        let existing = sqlx::query_scalar::<_, Uuid>(
            "SELECT id FROM covalence.nodes \
             WHERE fingerprint = $1 AND node_type = 'source' AND namespace = $2",
        )
        .bind(&fingerprint)
        .bind(&self.namespace)
        .fetch_optional(&self.pool)
        .await?;

        if let Some(id) = existing {
            return self.get(id).await;
        }

        // 3. Create node
        let id = Uuid::new_v4();
        let now = Utc::now();
        let reliability = req.reliability.unwrap_or_else(|| {
            default_reliability(req.source_type.as_deref(), req.capture_method.as_deref())
        });
        let mut metadata = req.metadata.unwrap_or(serde_json::json!({}));
        // Persist capture_method into metadata so callers can read it back.
        if let Some(ref cm) = req.capture_method {
            metadata["capture_method"] = serde_json::json!(cm);
        }
        let source_type = req.source_type.unwrap_or_else(|| "document".into());
        let content_hash = hex::encode(Sha256::digest(req.content.as_bytes()));
        let size_tokens = (req.content.split_whitespace().count() as f64 / 0.75) as i32;

        sqlx::query(
            "INSERT INTO covalence.nodes \
             (id, node_type, title, content, status, source_type, reliability, \
              fingerprint, content_hash, size_tokens, metadata, \
              confidence, namespace, \
              created_at, modified_at, accessed_at) \
             VALUES ($1, 'source', $2, $3, 'active', $4, $5, $6, $7, $8, $9, $10, $11, $12, $12, $12)",
        )
        .bind(id)
        .bind(&req.title)
        .bind(&req.content)
        .bind(&source_type)
        .bind(reliability as f64)
        .bind(&fingerprint)
        .bind(&content_hash)
        .bind(size_tokens)
        .bind(&metadata)
        .bind(reliability as f64)
        .bind(&self.namespace)
        .bind(now)
        .execute(&self.pool)
        .await?;

        // 4. Create AGE vertex
        if let Err(e) = self
            .graph
            .create_vertex(id, NodeType::Source, serde_json::json!({}))
            .await
        {
            tracing::warn!(error = %e, source_id = %id, "failed to create AGE vertex for source");
        }

        // 5. Create CAPTURED_IN edge if session provided
        if let Some(session_id) = req.session_id
            && let Err(e) = self
                .graph
                .create_edge(
                    id,
                    session_id,
                    EdgeType::CapturedIn,
                    1.0,
                    "algorithmic",
                    serde_json::json!({}),
                )
                .await
        {
            tracing::warn!(error = %e, "failed to create CAPTURED_IN edge");
        }

        // 6. Enqueue slow-path tasks
        self.enqueue_slow_path(id, &source_type).await?;

        self.get(id).await
    }

    /// Get a source by ID.
    pub async fn get(&self, id: Uuid) -> AppResult<SourceResponse> {
        let row = sqlx::query(
            "SELECT id, title, content, source_type, status, \
             confidence, reliability, fingerprint, metadata, version, \
             created_at, modified_at \
             FROM covalence.nodes WHERE id = $1 AND node_type = 'source' AND namespace = $2",
        )
        .bind(id)
        .bind(&self.namespace)
        .fetch_optional(&self.pool)
        .await?
        .ok_or_else(|| AppError::NotFound(format!("source {id}")))?;

        Ok(source_from_row(&row))
    }

    /// List sources with optional filters.
    pub async fn list(&self, params: ListParams) -> AppResult<Vec<SourceResponse>> {
        let limit = params.limit.unwrap_or(20).min(100);
        let escaped_ns = self.namespace.replace('\'', "''");
        let mut sql = format!(
            "SELECT id, title, content, source_type, status, \
             confidence, reliability, fingerprint, metadata, version, \
             created_at, modified_at \
             FROM covalence.nodes WHERE node_type = 'source' AND namespace = '{escaped_ns}'",
        );

        if let Some(ref st) = params.source_type {
            sql.push_str(&format!(" AND source_type = '{st}'"));
        }
        if let Some(ref status) = params.status {
            sql.push_str(&format!(" AND status = '{status}'"));
        }
        if let Some(ref q) = params.q {
            sql.push_str(&format!(
                " AND content_tsv @@ websearch_to_tsquery('english', '{}')",
                q.replace('\'', "''")
            ));
        }
        if let Some(cursor) = params.cursor {
            sql.push_str(&format!(" AND id > '{cursor}'"));
        }
        sql.push_str(&format!(" ORDER BY created_at DESC LIMIT {limit}"));

        let rows = sqlx::query(&sql).fetch_all(&self.pool).await?;
        Ok(rows.iter().map(source_from_row).collect())
    }

    /// Delete a source (hard delete with cascade).
    pub async fn delete(&self, id: Uuid) -> AppResult<()> {
        // Delete AGE vertex (cascades AGE-layer edges)
        if let Err(e) = self.graph.delete_vertex(id).await {
            tracing::warn!(error = %e, "failed to delete AGE vertex for source {id}");
        }

        // ── Relational FK cleanup (order matters) ──────────────────────────
        //
        // 1. contentions — references both nodes(id) AND edges(id); must come
        //    before edges.
        sqlx::query(
            "DELETE FROM covalence.contentions \
             WHERE node_id = $1 OR source_node_id = $1",
        )
        .bind(id)
        .execute(&self.pool)
        .await?;

        // 2. edges — `graph.delete_vertex()` above already removes both the AGE
        //    vertex and the SQL edges mirror in `covalence.edges`.  A raw DELETE
        //    here would be a bypass of the GraphRepository layer (covalence#28).

        // 3. slow_path_queue — references nodes(id); no CASCADE.
        sqlx::query("DELETE FROM covalence.slow_path_queue WHERE node_id = $1")
            .bind(id)
            .execute(&self.pool)
            .await?;

        // 4. usage_traces — references nodes(id); no CASCADE.
        sqlx::query("DELETE FROM covalence.usage_traces WHERE node_id = $1")
            .bind(id)
            .execute(&self.pool)
            .await?;

        // 5. session_nodes — references nodes(id); no CASCADE.
        sqlx::query("DELETE FROM covalence.session_nodes WHERE node_id = $1")
            .bind(id)
            .execute(&self.pool)
            .await?;

        // 6. node_embeddings — has ON DELETE CASCADE but delete explicitly for
        //    clarity (idempotent).
        sqlx::query("DELETE FROM covalence.node_embeddings WHERE node_id = $1")
            .bind(id)
            .execute(&self.pool)
            .await?;

        // 7. Delete the node itself.
        let result =
            sqlx::query("DELETE FROM covalence.nodes WHERE id = $1 AND node_type = 'source'")
                .bind(id)
                .execute(&self.pool)
                .await?;

        if result.rows_affected() == 0 {
            return Err(AppError::NotFound(format!("source {id}")));
        }

        Ok(())
    }

    /// Enqueue slow-path tasks for a new source.
    async fn enqueue_slow_path(&self, source_id: Uuid, _source_type: &str) -> AppResult<()> {
        // Queue embedding generation
        sqlx::query(
            "INSERT INTO covalence.slow_path_queue (id, task_type, node_id, priority, status) \
             VALUES ($1, 'embed', $2, 3, 'pending')",
        )
        .bind(Uuid::new_v4())
        .bind(source_id)
        .execute(&self.pool)
        .await?;

        // Queue contention check
        sqlx::query(
            "INSERT INTO covalence.slow_path_queue (id, task_type, node_id, priority, status) \
             VALUES ($1, 'contention_check', $2, 5, 'pending')",
        )
        .bind(Uuid::new_v4())
        .bind(source_id)
        .execute(&self.pool)
        .await?;

        // Queue edge inference (runs after embed due to lower priority)
        sqlx::query(
            "INSERT INTO covalence.slow_path_queue (id, task_type, node_id, priority, status) \
             VALUES ($1, 'infer_edges', $2, 2, 'pending')",
        )
        .bind(Uuid::new_v4())
        .bind(source_id)
        .execute(&self.pool)
        .await?;

        Ok(())
    }
}

fn source_from_row(row: &PgRow) -> SourceResponse {
    let metadata: serde_json::Value = row.get("metadata");
    let capture_method = metadata
        .get("capture_method")
        .and_then(|v| v.as_str())
        .map(str::to_owned);
    SourceResponse {
        id: row.get("id"),
        node_type: "source".into(),
        title: row.get("title"),
        content: row.get("content"),
        source_type: row.get("source_type"),
        status: row.get("status"),
        confidence: row.get::<Option<f64>, _>("confidence").unwrap_or(0.5) as f32,
        reliability: row.get::<Option<f64>, _>("reliability").unwrap_or(0.5) as f32,
        fingerprint: row
            .get::<Option<String>, _>("fingerprint")
            .unwrap_or_default(),
        metadata,
        version: row.get::<Option<i32>, _>("version").unwrap_or(1),
        created_at: row.get("created_at"),
        modified_at: row.get("modified_at"),
        capture_method,
    }
}

/// Default reliability by source type and optional capture method (SPEC §5.4 + issue #37).
///
/// # Intentionality adjustments
///
/// | capture_method | source_type    | reliability |
/// |----------------|----------------|-------------|
/// | `"manual"`     | `observation`  | 0.65 ↑      |
/// | `"manual"`     | `conversation` | 0.65 ↑      |
/// | `"auto"`       | `observation`  | 0.25 ↓      |
/// | `"auto"`       | `conversation` | 0.30 ↓      |
/// | any / `None`   | everything else| type default|
fn default_reliability(source_type: Option<&str>, capture_method: Option<&str>) -> f32 {
    match capture_method {
        Some("manual") => match source_type {
            Some("observation") => 0.65,
            Some("conversation") => 0.65,
            // All other types are already high-signal — keep type defaults.
            _ => type_reliability(source_type),
        },
        Some("auto") => match source_type {
            Some("observation") => 0.25,
            Some("conversation") => 0.30,
            _ => type_reliability(source_type),
        },
        // "system" or None: use unmodified type defaults.
        _ => type_reliability(source_type),
    }
}

/// Baseline reliability by source type alone (Valence v2 defaults).
fn type_reliability(source_type: Option<&str>) -> f32 {
    match source_type {
        Some("document") | Some("code") => 0.8,
        Some("tool_output") => 0.7,
        Some("user_input") => 0.75,
        Some("web") => 0.6,
        Some("conversation") => 0.5,
        Some("observation") => 0.4,
        _ => 0.5,
    }
}
