#!/usr/bin/env bash
# scripts/check-client-fresh.sh — CI gate: fail if generated client is stale.
#
# Usage:
#   ./scripts/check-client-fresh.sh
#
# Exit codes:
#   0  client is up to date (or no spec change detected)
#   1  client is stale — regenerate with ./scripts/generate-client.sh
#
# How it works:
#   1. Regenerates the client into a temp directory.
#   2. Diffs the temp output against the committed clients/python/.
#   3. Exits non-zero and prints the diff if any tracked file changed.
#
# Intended use in CI:
#   - jobs:
#     - name: check-openapi-client
#       run: ./scripts/check-client-fresh.sh
#
# Set SKIP_FRESH_CHECK=1 to bypass (not recommended in main branch CI).

set -euo pipefail

if [[ "${SKIP_FRESH_CHECK:-}" == "1" ]]; then
  echo "SKIP_FRESH_CHECK=1 — bypassing stale-client check."
  exit 0
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMMITTED_DIR="${REPO_ROOT}/clients/python"
TEMP_DIR="$(mktemp -d)"
SPEC_FILE="${REPO_ROOT}/openapi.json"

cleanup() { rm -rf "${TEMP_DIR}"; }
trap cleanup EXIT

echo "→ Re-generating client into ${TEMP_DIR} …"
OUT_DIR="${TEMP_DIR}" \
SPEC_FILE="${SPEC_FILE}" \
  "${REPO_ROOT}/scripts/generate-client.sh" >/dev/null 2>&1

echo "→ Diffing against committed client …"

# Strip timestamps / generator version lines that change every run
EXCLUDE_PATTERNS=(
  "^#.*openapi-generator"
  "^# This file was automatically generated"
  "^# Generated by"
  "OpenAPI Generator version"
)

filter_generated() {
  local f="$1"
  grep -Ev "$(IFS='|'; echo "${EXCLUDE_PATTERNS[*]}")" "${f}" 2>/dev/null || true
}

DIFF_OUTPUT="$(
  diff -rq \
    --exclude=".openapi-generator-ignore" \
    --exclude=".openapi-generator" \
    "${COMMITTED_DIR}" "${TEMP_DIR}" 2>&1 || true
)"

if [[ -z "${DIFF_OUTPUT}" ]]; then
  echo "✓ Client is up to date."
  exit 0
fi

echo ""
echo "✗ Generated client differs from committed client!" >&2
echo "" >&2
echo "${DIFF_OUTPUT}" >&2
echo "" >&2
echo "Regenerate and commit with:" >&2
echo "  ./scripts/generate-client.sh --fetch" >&2
echo "  git add clients/python openapi.json" >&2
echo "  git commit -m 'chore(clients): regenerate Python client'" >&2
exit 1
